name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        run: go generate

      - name: "自动同步文件夹到我的服务器"
          uses: wangyucode/sftp-upload-action@v1.3.2
          with:
            host: ${{ secrets.SERVER_IP }}
            port: 22
            username: ${{ secrets.USERNAME }}
            privateKey: ${{ secrets.PRIVATE_KEY }}
            localDir: "dist"
            remoteDir: ${{ secrets.SERVER_DESTINATION }}